[package]
name = "remote-input"
version = "0.2.0"
edition = "2024"
description = "A lightweight daemon that lets you type on your phone and paste into your Linux desktop"

[dependencies]
tokio = { version = "1", default-features = false, features = ["rt-multi-thread", "net", "sync", "signal", "macros"] }
axum = { version = "0.8", default-features = false, features = ["ws", "http1"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", default-features = false, features = ["env-filter", "fmt", "ansi"] }
clap = { version = "4", default-features = false, features = ["derive", "std", "help", "usage", "error-context"] }
anyhow = "1"
local-ip-address = "0.6"
rcgen = "0.14.8"
axum-server = { version = "0.8.0", default-features = false, features = ["tls-rustls"] }
qr2term = "0.3.3"
rust-embed = { version = "8", default-features = false }
mime_guess = "2"

[target.'cfg(target_os = "linux")'.dependencies]
evdev = { version = "0.13", default-features = false }

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61.2", features = ["Win32_Foundation", "Win32_System_DataExchange", "Win32_System_Memory", "Win32_System_Ole"] }

[dev-dependencies]
tokio-tungstenite = "0.29"
tower = { version = "0.5", features = ["util"] }
serde_json = "1"
futures-util = "0.3"
reqwest = { version = "0.12", default-features = false, features = ["default-tls"] }

[profile.release]
strip = true
lto = true
codegen-units = 1
