use std::net::IpAddr;

/// Print the styled startup banner with URL and QR code.
pub fn print(local_ip: IpAddr, port: u16, use_http: bool) {
    let url = if use_http {
        format!("http://{local_ip}:{port}")
    } else {
        format!("https://{local_ip}:{port}")
    };

    let bold = "\x1b[1m";
    let cyan = "\x1b[36m";
    let yellow = "\x1b[33m";
    let green = "\x1b[32m";
    let dim = "\x1b[2m";
    let reset = "\x1b[0m";

    eprintln!();
    eprintln!("  {bold}{cyan}Remote Input{reset}");
    eprintln!();
    eprintln!("  {green}Open on your phone:{reset}");
    eprintln!("  {green}→{reset} {bold}{url}{reset}");
    eprintln!();

    if use_http {
        eprintln!("  {yellow}⚠ Running in HTTP mode (unencrypted).{reset}");
        eprintln!("  {dim}  Traffic can be intercepted on the LAN.{reset}");
        eprintln!("  {dim}  Remove --http to use HTTPS instead.{reset}");
    } else {
        eprintln!("  {dim}The browser may warn that the certificate is untrusted.{reset}");
        eprintln!("  {dim}This is normal — it is a self-signed cert generated by{reset}");
        eprintln!("  {dim}this program. Your input is encrypted and private.{reset}");
    }

    eprintln!();
    eprintln!("  {dim}Scan QR code:{reset}");
    if let Ok(qr) = qr2term::generate_qr_string(&url) {
        for line in qr.lines() {
            eprintln!("  {line}");
        }
    }
    eprintln!();
    eprintln!("  {dim}Waiting for connection...{reset}");
    eprintln!();
}
